---
# https://taskfile.dev

version: '3'

tasks:
  install-yay:
    cmds:
      - git clone https://aur.archlinux.org/yay-bin.git
      - cd yay-bin && makepkg -si
      - defer: rm -rf yay-bin
      - yay -Y --gendb
      - yay -Syu --devel
      - yay -Y --devel --save

  install-i3:
    cmds:
      - yay -S --needed --noconfirm xorg-server xorg-xev xorg-xinit xorg-xrandr xorg-xset xorg-font-util i3-wm i3blocks i3blocks-contrib rofi betterlockscreen

  install-alacritty:
    cmds:
      - yay -S --needed --noconfirm alacritty

  install-tabby:
    cmds:
      - yay -S --needed --noconfirm tabby-bin

  install-fonts:
    cmds:
      - yay -S --needed --noconfirm ttf-inconsolata-go-nerd ttf-firacode-nerd ttf-font-awesome ttf-dejavu ttf-roboto noto-fonts-emoji

  install-zsh:
    cmds:
      - yay -S --needed --noconfirm zsh zsh-nix-shell nix-zsh-completions spaceship-prompt zsh-syntax-highlighting zsh-autosuggestions exa

  install:
    cmds:
      - task: install-yay
      - task: install-i3
      - task: install-tabby
      - task: install-fonts
      - task: install-zsh
